### ISSUE TITLE
Uncaught TypeError: Cannot set property 'onchange' of null

### ISSUE THREAD

**Issue by maxdrei** [ebidel/blog#21]
Hi Eric, got this err, when I ran your code from https://ericbidelman.com/posts/2011/08/reading-mp3-id3-tags-in-javascript in Chrome 89.x. Could you support me, please? Thx and regards. Marcus.

**Comment by ebidel** [comment]
That article is pretty old. It's quite possible some of the code no longer works or has changed API surface.

**Comment by maxdrei** [comment]
Ok. Thx
