### ISSUE TITLE
Consider adding an RSS feed

### ISSUE THREAD

**Issue by simevidas** [ebidel/blog#5]
When I paste the URL of your latest article, 

https://ericbidelman.com/posts/2019/02/pptrstagingserver,

into my feed reader (Feedly), I only get a feed from Tumblr that seems to be out of date.

If you don’t have a new RSS file for the blog, consider adding one, for folks like me who like to get notified when new articles are published on the blog. 😊

**Comment by ebidel** [comment]
https://ericbidelman.com/rss.xml
