### ISSUE TITLE
Update job position title

### ISSUE THREAD

**Issue by d2s** [ebidel/blog#6]
Noticed your [tweet](https://twitter.com/ebidel/status/1101191475189039109) about moving to the new job. Might make sense to update the personal website's introduction text paragraphs with the new position. Following files mention your previous job position:

- https://github.com/ebidel/blog/blob/557461e41da6057796f6f40e0ceb8d27e3c96857/templates/pages/index.html#L58

- https://github.com/ebidel/blog/blob/39982d21e2e42f1fd67d33a86bbf111c1078061a/templates/pages/about.html#L53-L55

**Comment by ebidel** [comment]
Ha you're fast. Thanks for the heads up.

**Comment by ebidel** [comment]
Fixed in https://github.com/ebidel/blog/commit/415431a6df51866c1e1fca6bbeb8e6044a429203
